In [1]:
import os  
import numpy as np 
import cv2 
from tensorflow.keras.utils import to_categorical
#their is function to convert into categorical to solve the problem of precedence

In [7]:
#saving the model in file 
# model  = load_model("model.h5")
# label = np.load("labels.npy")

In [3]:
from keras.layers import Input, Dense
from keras.models import Model
# model  = load_model("model.h5")
# label = np.load("labels.npy")

is_init = False
size = -1

label = [] #list
dictionary = {} #dict
c = 0

for i in os.listdir():   #to access data collection code in single directory
    if i.split(".")[-1] == "npy" and not(i.split(".")[0] == "labels"):  ##accessing last file
        if not(is_init):
            is_init = True 
            X = np.load(i) #loading the file input data
            size = X.shape[0]
            y = np.array([i.split('.')[0]]*size).reshape(-1,1) #list of accessing one variable i.e happy
        else:
            X = np.concatenate((X, np.load(i)))
            y = np.concatenate((y, np.array([i.split('.')[0]]*size).reshape(-1,1)))
            
        label.append(i.split('.')[0])
        dictionary[i.split('.')[0]] = c  
        c = c+1
        
   #print(dictionary) 
   # print(label)


for i in range(y.shape[0]):  #convering y into integer
    y[i, 0] = dictionary[y[i, 0]] #ith row and zeroth column   
y = np.array(y, dtype="int32") #converting into int


# print(y)

###  hello = 0 nope = 1 ---> [1,0] ... [0,1] #to solve precedence problem

y = to_categorical(y)
# print(y)

X_new = X.copy()
y_new = y.copy()
counter = 0 

cnt = np.arange(X.shape[0]) #we r arranging data
np.random.shuffle(cnt) #shuffle cnt

# print(y)

for i in cnt: #shuffle data
    X_new[counter] = X[i]  #particular shuffle value at zeroth position
    y_new[counter] = y[i]
    counter = counter + 1 #at particular index
    
print(y) #we have got a random samplind data
print(y_new)


ip = Input(shape=(X.shape[1]))  #input layer

m = Dense(512, activation="relu")(ip) #giving activation as relu
m = Dense(256, activation="relu")(m) #256 neurons

op = Dense(y.shape[1], activation="softmax")(m) #winning column 1
# #we have used softmax activation function so that to find probabilities of top layer and sum up to one first class ,second color
# m is the middle layer previous

model = Model(inputs=ip, outputs=op)

model.compile(optimizer='rmsprop', loss="categorical_crossentropy", metrics=['acc'])
#we have used loss that shows how well ur model works on given dataset
#we have a categorical data i.e why we used categoricalcrossentropy
#rmsprop optimizer is used to accelrate the process of optimaztion
#rmsprop is used to accelrate the optimization process
model.fit(X, y, epochs=50)


model.save("model.h5")  #saving model
np.save("labels.npy", np.array(label))


[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]
Epoch 1/50
22/22 [==============================] - 2s 18ms/step - loss: 1.7104 - acc: 0.3529
Epoch 2/50
22/22 [==============================] - 0s 16ms/step - loss: 1.1453 - acc: 0.6043
Epoch 3/50
22/22 [==============================] - 0s 14ms/step - loss: 0.8710 - acc: 0.6986
Epoch 4/50
22/22 [==============================] - 0s 15ms/step - loss: 0.7249 - acc: 0.7429
Epoch 5/50
22/22 [==============================] - 0s 17ms/step - loss: 0.6533 - acc: 0.7729
Epoch 6/50
22/22 [==============================] - 0s 15ms/step - loss: 0.6250 - acc: 0.7643
Epoch 7/50
22/22 [==============================] - 0s 16ms/step - loss: 0.5937 - acc: 0.8029
Epoch 8/50
22/22 [============

C:\Users\Mihir\anaconda3\envs\HandGestureRecognitionSystem\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
